=== vpinna80/VTL/vtl-meta/vtl-metabase/src/main/resources/it/bancaditalia/oss/vtl/impl/meta/json/vtl-dict-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://sdmx.org/vtl-dict-schema.json",
  "description": "VTL Dictionary JSON serialization schema",
  "version": "2.2.0",
  
  "$defs": {
    "vtl-id": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_.]*$|^'.*'$|^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*(\\([0-9]+(\\.[0-9]+)*(\\.[_+*~])?\\))?(:(\\.[A-Za-z0-9_])+)?$"
    },
    "identifiable": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/$defs/vtl-id" },
        "description": { "type": "string" }
      },
      "required": [ "name" ]
    },
    "has-role": {
      "type": "object",
      "properties": {
        "role": {
          "type": "string",
          "enum": [ "Identifier", "Measure", "Attribute", "Viral Attribute" ]
        }
      },
      "required": [ "role" ]
    }
  },
  
  "type": "object",
  "properties": {
    "schema-version": { "type": "string"},
    "data": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "structure": { "$ref": "#/$defs/vtl-id" },
          "components": { 
            "type": "array",
            "items": {
              "allOf": [ { "$ref": "#/$defs/identifiable" } ],
              "properties": {
                "subset": { "$ref": "#/$defs/vtl-id" },
                "nullable": { "type": "boolean" }
              },
              "required": [ "subset" ]
            }
          },
          "subset": { "$ref": "#/$defs/vtl-id" },
          "source": { "type": "string" }
        },
        "oneOf": [
          { "required": [ "structure" ], "not": { "required": [ "subset" ] } },
          { "required": [ "subset" ], "not": { "anyOf": [ { "required": [ "structure" ] }, { "required": [ "components" ] } ] } }
        ]
      }
    },
    "structures": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "components": {
            "type": "array",
            "items": {
              "allOf": [ { "$ref": "#/$defs/identifiable" }, { "$ref": "#/$defs/has-role" } ],
              "properties": {
                "nullable": { "type": "boolean" }
              }
            }
          }
        },
        "required": [ "components" ]
      }
    },
    "variables": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "domain": { "$ref": "#/$defs/vtl-id" }
        },
        "required": [ "domain" ]
      }
    },
    "domains": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "unevaluatedProperties": false,
        "oneOf": [
          {
            "properties": {
              "externalRef": { "type": "string" }
            },
            "required": [ "externalRef" ]
          }, {
            "properties": {
              "parent": { "$ref": "#/$defs/vtl-id" }
            },
            "required": [ "parent" ],
            "oneOf": [ 
              {
                "properties": {
                  "enumerated": { 
			        "type": "array",
			        "uniqueItems": true,
			        "minItems": 1,
			        "items": {
			          "oneOf": [
			          	{ "type": "string" },
			          	{ "allOf": [ { "$ref": "#/$defs/identifiable" } ] }
			          ]
			        }
                  }
                },
                "required": [ "enumerated" ]
              },
              {
                "properties": {
                  "described": { "type": "string" },
                  "mask": { "type": "string" }
                },
                "required": [ "described" ]
              }
            ]
          }
        ]
      }
    }
  },
  "required": [ "schema-version" ]
}

=== vpinna80/VTL/vtl-bundles/vtl-r/vtl-java2r/src/main/resources/it/bancaditalia/oss/vtl/util/examples/Time operators/Fill time series/examples.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "csv:ds_1.csv"
    },
    {
      "name": "ds_2",
      "structure": "DS_2",
      "source": "csv:ds_2.csv"
    },
    {
      "name": "ds_3",
      "structure": "DS_3",
      "source": "csv:ds_3.csv"
    },
    {
      "name": "ds_4",
      "structure": "DS_4",
      "source": "csv:ds_4.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_2",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_3",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_4",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "string"
    },
    {
      "name": "Id_2",
      "domain": "time"
    },
    {
      "name": "Me_1",
      "domain": "string"
    }
  ],
  "domains": []
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/Comparison operators/Greater than/examples/ex_2.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "csv:ds_1.csv"
    },
    {
      "name": "ex_2",
      "structure": "DS_r",
      "source": "csv:ex_2.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Id_3",
          "role": "Identifier"
        },
        {
          "name": "Id_4",
          "role": "Identifier"
        },
        {
          "name": "Id_5",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_r",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Id_3",
          "role": "Identifier"
        },
        {
          "name": "Id_4",
          "role": "Identifier"
        },
        {
          "name": "Id_5",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "integer"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Id_3",
      "domain": "time_period"
    },
    {
      "name": "Id_4",
      "domain": "string"
    },
    {
      "name": "Id_5",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "number"
    },
    {
      "name": "Me_2",
      "domain": "boolean"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/05 Comparison operators/equal/ex_1.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_2",
      "source": "csv:in_2.csv",
      "structure": "in_2_str"
    },
    {
      "name": "comparison_eq_1",
      "source": "csv:comparison_eq_1.csv",
      "structure": "comparison_eq_1_str"
    },
    {
      "name": "in_1",
      "source": "csv:in_1.csv",
      "structure": "in_1_str"
    },
    {
      "name": "ex_1",
      "structure": "ex_1_str",
      "source": "csv:ex_1.csv"
    }
  ],
  "structures": [
    {
      "name": "ex_1_str",
      "components": [
        {
          "name": "id1",
          "role": "Identifier"
        },
        {
          "name": "bool_var",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "in_2_str",
      "components": [
        {
          "name": "id1",
          "role": "Identifier"
        },
        {
          "name": "m1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "comparison_eq_1_str",
      "components": [
        {
          "name": "id1",
          "role": "Identifier"
        },
        {
          "name": "m1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "in_1_str",
      "components": [
        {
          "name": "id1",
          "role": "Identifier"
        },
        {
          "name": "m1",
          "role": "Measure"
        },
        {
          "name": "att1",
          "role": "Attribute"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "m1",
      "domain": "number"
    },
    {
      "name": "id1",
      "domain": "string"
    },
    {
      "name": "att1",
      "domain": "string"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/07 Time operators/stock_to_flow/ex_1.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_1",
      "source": "csv:in_1.csv",
      "structure": "in_1_str"
    },
    {
      "name": "ex_1",
      "structure": "ex_1_str",
      "source": "csv:ex_1.csv"
    }
  ],
  "structures": [
    {
      "name": "in_1_str",
      "components": [
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "me_1",
          "role": "Measure"
        },
        {
          "name": "id_daily",
          "role": "Identifier"
        }
      ]
    },
    {
      "name": "ex_1_str",
      "components": [
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "me_1",
          "role": "Measure"
        },
        {
          "name": "id_daily",
          "role": "Identifier"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_1",
      "domain": "string"
    },
    {
      "name": "res4",
      "domain": "boolean"
    },
    {
      "name": "res3",
      "domain": "boolean"
    },
    {
      "name": "res2",
      "domain": "boolean"
    },
    {
      "name": "id_3",
      "domain": "string"
    },
    {
      "name": "id_daily",
      "domain": "date"
    },
    {
      "name": "res1",
      "domain": "boolean"
    },
    {
      "name": "me_1",
      "domain": "number"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/General purpose operators/Membership/examples/ex_6-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_2",
      "structure": "DS_1",
      "source": "spark:csv:ds_2.csv"
    },
    {
      "name": "ex_6",
      "structure": "DS_r",
      "source": "spark:csv:ex_6.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        },
        {
          "name": "At_1",
          "role": "Viral Attribute"
        }
      ]
    },
    {
      "name": "DS_r",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "string_var",
          "role": "Measure"
        },
        {
          "name": "At_1",
          "role": "Viral Attribute"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "At_1",
      "domain": "string"
    },
    {
      "name": "Id_1",
      "domain": "integer"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "integer"
    },
    {
      "name": "Me_2",
      "domain": "integer"
    },
    {
      "name": "string_var",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/Join operators/Join/examples/ex_7-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "spark:csv:ds_1.csv"
    },
    {
      "name": "ds_3",
      "structure": "DS_3",
      "source": "spark:csv:ds_3.csv"
    },
    {
      "name": "ex_7",
      "structure": "DS_r",
      "source": "spark:csv:ex_7.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_3",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_r",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "integer"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "string"
    },
    {
      "name": "Me_2",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/Comparison operators/Element of/examples/ex_2-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "spark:csv:ds_1.csv"
    },
    {
      "name": "ex_2",
      "structure": "DS_r",
      "source": "spark:csv:ex_2.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_r",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "time_period"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "integer"
    },
    {
      "name": "Me_2",
      "domain": "boolean"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/Aggregate and Analytic operators/Aggregate invocation/examples/ex_4-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "spark:csv:ds_1.csv"
    },
    {
      "name": "ex_4",
      "structure": "DS_3",
      "source": "spark:csv:ex_4.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Id_3",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "At_1",
          "role": "Viral Attribute"
        }
      ]
    },
    {
      "name": "DS_3",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        },
        {
          "name": "Me_3",
          "role": "Measure"
        },
        {
          "name": "At_1",
          "role": "Viral Attribute"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "At_1",
      "domain": "string"
    },
    {
      "name": "Id_1",
      "domain": "time_period"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Id_3",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "integer"
    },
    {
      "name": "Me_2",
      "domain": "integer"
    },
    {
      "name": "Me_3",
      "domain": "integer"
    }
  ]
}
