=== vpinna80/VTL/vtl-meta/vtl-metabase/src/main/resources/it/bancaditalia/oss/vtl/impl/meta/json/vtl-dict-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://sdmx.org/vtl-dict-schema.json",
  "description": "VTL Dictionary JSON serialization schema",
  "version": "2.2.0",
  
  "$defs": {
    "vtl-id": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_.]*$|^'.*'$|^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*(\\([0-9]+(\\.[0-9]+)*(\\.[_+*~])?\\))?(:(\\.[A-Za-z0-9_])+)?$"
    },
    "identifiable": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/$defs/vtl-id" },
        "description": { "type": "string" }
      },
      "required": [ "name" ]
    },
    "has-role": {
      "type": "object",
      "properties": {
        "role": {
          "type": "string",
          "enum": [ "Identifier", "Measure", "Attribute", "Viral Attribute" ]
        }
      },
      "required": [ "role" ]
    }
  },
  
  "type": "object",
  "properties": {
    "schema-version": { "type": "string"},
    "data": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "structure": { "$ref": "#/$defs/vtl-id" },
          "components": { 
            "type": "array",
            "items": {
              "allOf": [ { "$ref": "#/$defs/identifiable" } ],
              "properties": {
                "subset": { "$ref": "#/$defs/vtl-id" },
                "nullable": { "type": "boolean" }
              },
              "required": [ "subset" ]
            }
          },
          "subset": { "$ref": "#/$defs/vtl-id" },
          "source": { "type": "string" }
        },
        "oneOf": [
          { "required": [ "structure" ], "not": { "required": [ "subset" ] } },
          { "required": [ "subset" ], "not": { "anyOf": [ { "required": [ "structure" ] }, { "required": [ "components" ] } ] } }
        ]
      }
    },
    "structures": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "components": {
            "type": "array",
            "items": {
              "allOf": [ { "$ref": "#/$defs/identifiable" }, { "$ref": "#/$defs/has-role" } ],
              "properties": {
                "nullable": { "type": "boolean" }
              }
            }
          }
        },
        "required": [ "components" ]
      }
    },
    "variables": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "domain": { "$ref": "#/$defs/vtl-id" }
        },
        "required": [ "domain" ]
      }
    },
    "domains": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "unevaluatedProperties": false,
        "oneOf": [
          {
            "properties": {
              "externalRef": { "type": "string" }
            },
            "required": [ "externalRef" ]
          }, {
            "properties": {
              "parent": { "$ref": "#/$defs/vtl-id" }
            },
            "required": [ "parent" ],
            "oneOf": [ 
              {
                "properties": {
                  "enumerated": { 
			        "type": "array",
			        "uniqueItems": true,
			        "minItems": 1,
			        "items": {
			          "oneOf": [
			          	{ "type": "string" },
			          	{ "allOf": [ { "$ref": "#/$defs/identifiable" } ] }
			          ]
			        }
                  }
                },
                "required": [ "enumerated" ]
              },
              {
                "properties": {
                  "described": { "type": "string" },
                  "mask": { "type": "string" }
                },
                "required": [ "described" ]
              }
            ]
          }
        ]
      }
    }
  },
  "required": [ "schema-version" ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/10 Aggregate and Analytic operators/sum/ex_1.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_1",
      "source": "csv:in_1.csv",
      "structure": "in_1_str"
    },
    {
      "name": "ex_1",
      "structure": "ex_1_str",
      "source": "csv:ex_1.csv"
    }
  ],
  "structures": [
    {
      "name": "in_1_str",
      "components": [
        {
          "name": "id1",
          "role": "Identifier"
        },
        {
          "name": "id2",
          "role": "Identifier"
        },
        {
          "name": "m1",
          "role": "Measure"
        },
        {
          "name": "att1",
          "role": "Attribute"
        }
      ]
    },
    {
      "name": "ex_1_str",
      "components": [
        {
          "name": "id2",
          "role": "Identifier"
        },
        {
          "name": "m1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "m1",
      "domain": "number"
    },
    {
      "name": "m2",
      "domain": "number"
    },
    {
      "name": "id1",
      "domain": "string"
    },
    {
      "name": "att1",
      "domain": "string"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    },
    {
      "name": "id2",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/04 Numeric operators/ceil/ex_1-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "number_test2",
      "source": "spark:csv:in_1.csv",
      "structure": "in_1_str"
    },
    {
      "name": "ex_1",
      "structure": "in_1_str",
      "source": "spark:csv:ex_1.csv"
    }
  ],
  "structures": [
    {
      "name": "in_1_str",
      "components": [
        {
          "name": "id1",
          "role": "Identifier"
        },
        {
          "name": "m1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "m1",
      "domain": "number"
    },
    {
      "name": "id1",
      "domain": "string"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-r/RVTL/src/main/resources/R/tests/testthat/data/ex_r_json.json
{
  "schema-version": "2.2.0", 
  "data": [
    {
      "name": "ds_r_json",
      "structure": "DS_1"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "integer"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "integer"
    },
    {
      "name": "Me_2",
      "domain": "number"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/03 String operators/trim/ex_4.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_4",
      "source": "csv:in_4.csv",
      "structure": "in_4_str"
    },
    {
      "name": "ex_4",
      "structure": "ex_4_str",
      "source": "csv:ex_4.csv"
    }
  ],
  "structures": [
    {
      "name": "in_4_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "text_2",
          "role": "Measure"
        },
        {
          "name": "text_1",
          "role": "Measure"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        }
      ]
    },
    {
      "name": "ex_4_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "text_3",
          "role": "Measure"
        },
        {
          "name": "text_2",
          "role": "Measure"
        },
        {
          "name": "text_1",
          "role": "Measure"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "text_4",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_2",
      "domain": "string"
    },
    {
      "name": "id_3",
      "domain": "string"
    },
    {
      "name": "id_1",
      "domain": "integer"
    },
    {
      "name": "text_3",
      "domain": "string"
    },
    {
      "name": "text_4",
      "domain": "string"
    },
    {
      "name": "text_1",
      "domain": "string"
    },
    {
      "name": "text_2",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/05 Comparison operators/between/ex_2-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_2",
      "source": "spark:csv:in_2.csv",
      "structure": "in_2_str"
    },
    {
      "name": "ex_2",
      "structure": "ex_2_str",
      "source": "spark:csv:ex_2.csv"
    }
  ],
  "structures": [
    {
      "name": "in_2_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "year",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "ex_2_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "year",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        },
        {
          "name": "btwn",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_1",
      "domain": "string"
    },
    {
      "name": "year",
      "domain": "number"
    },
    {
      "name": "btwn",
      "domain": "boolean"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    },
    {
      "name": "num_1",
      "domain": "number"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/03 String operators/upper_lower/ex_1.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_1",
      "source": "csv:in_1.csv",
      "structure": "in_1_str"
    },
    {
      "name": "ex_1",
      "structure": "ex_1_str",
      "source": "csv:ex_1.csv"
    }
  ],
  "structures": [
    {
      "name": "in_1_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "text_2",
          "role": "Measure"
        },
        {
          "name": "text_1",
          "role": "Measure"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        }
      ]
    },
    {
      "name": "ex_1_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "text_2",
          "role": "Measure"
        },
        {
          "name": "text_1",
          "role": "Measure"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "text_low",
          "role": "Measure"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "text_up",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_2",
      "domain": "string"
    },
    {
      "name": "res2",
      "domain": "boolean"
    },
    {
      "name": "text_low",
      "domain": "string"
    },
    {
      "name": "id_3",
      "domain": "string"
    },
    {
      "name": "id_1",
      "domain": "integer"
    },
    {
      "name": "res1",
      "domain": "boolean"
    },
    {
      "name": "text_up",
      "domain": "string"
    },
    {
      "name": "text_1",
      "domain": "string"
    },
    {
      "name": "text_2",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-meta/vtl-metasdmx/src/test/resources/it/bancaditalia/oss/vtl/impl/meta/test.json
{
	"schema-version": "2.2.0",
	"data": [{
		"name": "DS_1",
		"structure": "DS_1_str"
	}, {
		"name": "DS_2",
		"structure": "DS_2_str"
	}],	"structures": [{
		"name": "DS_1_str",
		"components": [{
			"name": "Id_1",
			"role": "Identifier"
		}, {
			"name": "Me_1",
			"role": "Measure"
		}, {
			"name": "At_1",
			"role": "Attribute"
		}, {
			"name": "Va_1",
			"role": "Viral Attribute"
		}]
	}, {
		"name": "DS_2_str",
		"components": [{
			"name": "Id_2",
			"role": "Identifier"
		}, {
			"name": "Me_2",
			"role": "Measure"
		}, {
			"name": "At_1",
			"role": "Attribute"
		}, {
			"name": "Va_1",
			"role": "Viral Attribute"
		}]
	}],	"variables": [{
		"name": "Id_1",
		"domain": "string"
	}, {
		"name": "Id_2",
		"domain": "string"
	}, {
		"name": "Me_1",
		"domain": "number"
	}, {
		"name": "Me_2",
		"domain": "integer"
	}, {
		"name": "At_1",
		"domain": "ECB:CL_CURRENCY(1.0)"
	}, {
		"name": "Va_1",
		"domain": "VD_1"
	}],	"domains": [{
		"name": "VD_1",
		"parent": "string",
		"enumerated": [ "A", "B", "C", "D", "E", "F", "G", "H", "I", "J" ]
	}]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/10 Aggregate and Analytic operators/lag/ex_1-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_1",
      "source": "spark:csv:in_1.csv",
      "structure": "in_1_str"
    },
    {
      "name": "ex_1",
      "structure": "ex_1_str",
      "source": "spark:csv:ex_1.csv"
    }
  ],
  "structures": [
    {
      "name": "in_1_str",
      "components": [
        {
          "name": "edfdate",
          "role": "Identifier"
        },
        {
          "name": "mkmvid",
          "role": "Identifier"
        },
        {
          "name": "edf1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "ex_1_str",
      "components": [
        {
          "name": "edfdate",
          "role": "Identifier"
        },
        {
          "name": "mkmvid",
          "role": "Identifier"
        },
        {
          "name": "edf1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "edfdate",
      "domain": "date"
    },
    {
      "name": "edf1",
      "domain": "number"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    },
    {
      "name": "mkmvid",
      "domain": "string"
    }
  ]
}
