=== vpinna80/VTL/vtl-meta/vtl-metabase/src/main/resources/it/bancaditalia/oss/vtl/impl/meta/json/vtl-dict-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://sdmx.org/vtl-dict-schema.json",
  "description": "VTL Dictionary JSON serialization schema",
  "version": "2.2.0",
  
  "$defs": {
    "vtl-id": {
      "type": "string",
      "pattern": "^[A-Za-z_][A-Za-z0-9_.]*$|^'.*'$|^[A-Za-z_][A-Za-z0-9_.]*:[A-Za-z_][A-Za-z0-9_.]*(\\([0-9]+(\\.[0-9]+)*(\\.[_+*~])?\\))?(:(\\.[A-Za-z0-9_])+)?$"
    },
    "identifiable": {
      "type": "object",
      "properties": {
        "name": { "$ref": "#/$defs/vtl-id" },
        "description": { "type": "string" }
      },
      "required": [ "name" ]
    },
    "has-role": {
      "type": "object",
      "properties": {
        "role": {
          "type": "string",
          "enum": [ "Identifier", "Measure", "Attribute", "Viral Attribute" ]
        }
      },
      "required": [ "role" ]
    }
  },
  
  "type": "object",
  "properties": {
    "schema-version": { "type": "string"},
    "data": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "structure": { "$ref": "#/$defs/vtl-id" },
          "components": { 
            "type": "array",
            "items": {
              "allOf": [ { "$ref": "#/$defs/identifiable" } ],
              "properties": {
                "subset": { "$ref": "#/$defs/vtl-id" },
                "nullable": { "type": "boolean" }
              },
              "required": [ "subset" ]
            }
          },
          "subset": { "$ref": "#/$defs/vtl-id" },
          "source": { "type": "string" }
        },
        "oneOf": [
          { "required": [ "structure" ], "not": { "required": [ "subset" ] } },
          { "required": [ "subset" ], "not": { "anyOf": [ { "required": [ "structure" ] }, { "required": [ "components" ] } ] } }
        ]
      }
    },
    "structures": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "components": {
            "type": "array",
            "items": {
              "allOf": [ { "$ref": "#/$defs/identifiable" }, { "$ref": "#/$defs/has-role" } ],
              "properties": {
                "nullable": { "type": "boolean" }
              }
            }
          }
        },
        "required": [ "components" ]
      }
    },
    "variables": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "properties": {
          "domain": { "$ref": "#/$defs/vtl-id" }
        },
        "required": [ "domain" ]
      }
    },
    "domains": {
      "type": "array",
      "items": {
        "allOf": [ { "$ref": "#/$defs/identifiable" } ],
        "unevaluatedProperties": false,
        "oneOf": [
          {
            "properties": {
              "externalRef": { "type": "string" }
            },
            "required": [ "externalRef" ]
          }, {
            "properties": {
              "parent": { "$ref": "#/$defs/vtl-id" }
            },
            "required": [ "parent" ],
            "oneOf": [ 
              {
                "properties": {
                  "enumerated": { 
			        "type": "array",
			        "uniqueItems": true,
			        "minItems": 1,
			        "items": {
			          "oneOf": [
			          	{ "type": "string" },
			          	{ "allOf": [ { "$ref": "#/$defs/identifiable" } ] }
			          ]
			        }
                  }
                },
                "required": [ "enumerated" ]
              },
              {
                "properties": {
                  "described": { "type": "string" },
                  "mask": { "type": "string" }
                },
                "required": [ "described" ]
              }
            ]
          }
        ]
      }
    }
  },
  "required": [ "schema-version" ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/Time operators/Fill time series/examples/ex_5.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_3",
      "structure": "DS_3",
      "source": "csv:ds_3.csv"
    },
    {
      "name": "ex_5",
      "structure": "DS_r",
      "source": "csv:ex_5.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_3",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_r",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "string"
    },
    {
      "name": "Id_2",
      "domain": "time_period"
    },
    {
      "name": "Me_1",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-r/vtl-java2r/src/main/resources/it/bancaditalia/oss/vtl/util/examples/Clause operators/Unpivoting/examples.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "csv:ds_1.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "A",
          "role": "Measure"
        },
        {
          "name": "B",
          "role": "Measure"
        },
        {
          "name": "C",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "A",
      "domain": "integer"
    },
    {
      "name": "B",
      "domain": "integer"
    },
    {
      "name": "C",
      "domain": "integer"
    },
    {
      "name": "Id_1",
      "domain": "integer"
    }
  ],
  "domains": []
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/05 Comparison operators/greater_than/ex_3.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_7",
      "source": "csv:in_7.csv",
      "structure": "in_7_str"
    },
    {
      "name": "in_6",
      "source": "csv:in_6.csv",
      "structure": "in_6_str"
    },
    {
      "name": "ex_3",
      "structure": "gr_2_str",
      "source": "csv:ex_3.csv"
    }
  ],
  "structures": [
    {
      "name": "gr_2_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "gr",
          "role": "Measure"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "in_7_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "in_6_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_2",
      "domain": "string"
    },
    {
      "name": "gr",
      "domain": "boolean"
    },
    {
      "name": "id_3",
      "domain": "string"
    },
    {
      "name": "id_4",
      "domain": "string"
    },
    {
      "name": "id_1",
      "domain": "number"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    },
    {
      "name": "num_1",
      "domain": "number"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/04 Numeric operators/abs/ex_3.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_3",
      "source": "csv:in_3.csv",
      "structure": "in_3_str"
    },
    {
      "name": "ex_3",
      "structure": "ex_3_str",
      "source": "csv:ex_3.csv"
    }
  ],
  "structures": [
    {
      "name": "in_3_str",
      "components": [
        {
          "name": "time_period",
          "role": "Identifier"
        },
        {
          "name": "num_2",
          "role": "Measure"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "ex_3_str",
      "components": [
        {
          "name": "time_period",
          "role": "Identifier"
        },
        {
          "name": "abs_3",
          "role": "Measure"
        },
        {
          "name": "num_2",
          "role": "Measure"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "num_2",
      "domain": "number"
    },
    {
      "name": "time_period",
      "domain": "number"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    },
    {
      "name": "abs_3",
      "domain": "number"
    },
    {
      "name": "num_1",
      "domain": "number"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/06 Boolean operators/and/ex_2.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_3",
      "source": "csv:in_3.csv",
      "structure": "in_3_str"
    },
    {
      "name": "ex_2",
      "structure": "ex_2_str",
      "source": "csv:ex_2.csv"
    }
  ],
  "structures": [
    {
      "name": "ex_2_str",
      "components": [
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "me_1",
          "role": "Measure"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "andt",
          "role": "Measure"
        },
        {
          "name": "andf",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "in_3_str",
      "components": [
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "me_1",
          "role": "Measure"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_1",
          "role": "Identifier"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_1",
      "domain": "string"
    },
    {
      "name": "andt",
      "domain": "boolean"
    },
    {
      "name": "res2",
      "domain": "boolean"
    },
    {
      "name": "id_3",
      "domain": "string"
    },
    {
      "name": "andf",
      "domain": "boolean"
    },
    {
      "name": "me_1",
      "domain": "boolean"
    },
    {
      "name": "id_2",
      "domain": "number"
    },
    {
      "name": "id_4",
      "domain": "number"
    },
    {
      "name": "res1",
      "domain": "boolean"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/13 Clause operators/calc/ex_2.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_2",
      "source": "csv:in_2.csv",
      "structure": "in_2_str"
    },
    {
      "name": "ex_2",
      "structure": "ex_2_str",
      "source": "csv:ex_2.csv"
    }
  ],
  "structures": [
    {
      "name": "ex_2_str",
      "components": [
        {
          "name": "me_sum",
          "role": "Measure"
        },
        {
          "name": "exr_suffix",
          "role": "Measure"
        },
        {
          "name": "time_format",
          "role": "Attribute"
        },
        {
          "name": "freq",
          "role": "Measure"
        },
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id",
          "role": "Attribute"
        },
        {
          "name": "title",
          "role": "Attribute"
        },
        {
          "name": "unit_mult",
          "role": "Attribute"
        },
        {
          "name": "year",
          "role": "Identifier"
        },
        {
          "name": "unit",
          "role": "Attribute"
        },
        {
          "name": "currency",
          "role": "Measure"
        },
        {
          "name": "currency_denom",
          "role": "Measure"
        },
        {
          "name": "me_2",
          "role": "Measure"
        },
        {
          "name": "source_agency",
          "role": "Attribute"
        },
        {
          "name": "me_1",
          "role": "Measure"
        },
        {
          "name": "exr_type",
          "role": "Measure"
        },
        {
          "name": "decimals",
          "role": "Attribute"
        },
        {
          "name": "collection",
          "role": "Attribute"
        },
        {
          "name": "obs_status",
          "role": "Attribute"
        }
      ]
    },
    {
      "name": "in_2_str",
      "components": [
        {
          "name": "exr_suffix",
          "role": "Measure"
        },
        {
          "name": "time_format",
          "role": "Attribute"
        },
        {
          "name": "freq",
          "role": "Measure"
        },
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id",
          "role": "Attribute"
        },
        {
          "name": "title",
          "role": "Attribute"
        },
        {
          "name": "unit_mult",
          "role": "Attribute"
        },
        {
          "name": "year",
          "role": "Identifier"
        },
        {
          "name": "unit",
          "role": "Attribute"
        },
        {
          "name": "currency",
          "role": "Measure"
        },
        {
          "name": "currency_denom",
          "role": "Measure"
        },
        {
          "name": "me_2",
          "role": "Measure"
        },
        {
          "name": "source_agency",
          "role": "Attribute"
        },
        {
          "name": "me_1",
          "role": "Measure"
        },
        {
          "name": "exr_type",
          "role": "Measure"
        },
        {
          "name": "decimals",
          "role": "Attribute"
        },
        {
          "name": "collection",
          "role": "Attribute"
        },
        {
          "name": "obs_status",
          "role": "Attribute"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "unit",
      "domain": "string"
    },
    {
      "name": "decimals",
      "domain": "string"
    },
    {
      "name": "currency_denom",
      "domain": "string"
    },
    {
      "name": "source_agency",
      "domain": "string"
    },
    {
      "name": "exr_suffix",
      "domain": "string"
    },
    {
      "name": "collection",
      "domain": "string"
    },
    {
      "name": "title",
      "domain": "string"
    },
    {
      "name": "freq",
      "domain": "string"
    },
    {
      "name": "id_1",
      "domain": "string"
    },
    {
      "name": "id",
      "domain": "string"
    },
    {
      "name": "exr_type",
      "domain": "string"
    },
    {
      "name": "time_format",
      "domain": "string"
    },
    {
      "name": "obs_status",
      "domain": "string"
    },
    {
      "name": "year",
      "domain": "integer"
    },
    {
      "name": "unit_mult",
      "domain": "string"
    },
    {
      "name": "currency",
      "domain": "string"
    },
    {
      "name": "me_2",
      "domain": "integer"
    },
    {
      "name": "me_sum",
      "domain": "number"
    },
    {
      "name": "me_1",
      "domain": "number"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/examples/Join operators/Join/examples/ex_5.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "ds_1",
      "structure": "DS_1",
      "source": "csv:ds_1.csv"
    },
    {
      "name": "ds_2",
      "structure": "DS_2",
      "source": "csv:ds_2.csv"
    },
    {
      "name": "ex_5",
      "structure": "DS_r",
      "source": "csv:ex_5.csv"
    }
  ],
  "structures": [
    {
      "name": "DS_1",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_2",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1A",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "DS_r",
      "components": [
        {
          "name": "Id_1",
          "role": "Identifier"
        },
        {
          "name": "Id_2",
          "role": "Identifier"
        },
        {
          "name": "Me_1",
          "role": "Measure"
        },
        {
          "name": "Me_1A",
          "role": "Measure"
        },
        {
          "name": "Me_2",
          "role": "Measure"
        },
        {
          "name": "Me_4",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "Id_1",
      "domain": "integer"
    },
    {
      "name": "Id_2",
      "domain": "string"
    },
    {
      "name": "Me_1",
      "domain": "string"
    },
    {
      "name": "Me_1A",
      "domain": "string"
    },
    {
      "name": "Me_2",
      "domain": "string"
    },
    {
      "name": "Me_4",
      "domain": "string"
    }
  ]
}

=== vpinna80/VTL/vtl-bundles/vtl-coverage/src/test/resources/it/bancaditalia/oss/vtl/coverage/tests/05 Comparison operators/lesser_than/ex_2-spark.json
{
  "schema-version": "2.2.0",
  "data": [
    {
      "name": "in_4",
      "source": "spark:csv:in_4.csv",
      "structure": "in_4_str"
    },
    {
      "name": "in_3",
      "source": "spark:csv:in_3.csv",
      "structure": "in_3_str"
    },
    {
      "name": "ex_2",
      "structure": "ex_2_str",
      "source": "spark:csv:ex_2.csv"
    }
  ],
  "structures": [
    {
      "name": "in_4_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "ex_2_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "le",
          "role": "Measure"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    },
    {
      "name": "in_3_str",
      "components": [
        {
          "name": "id_1",
          "role": "Identifier"
        },
        {
          "name": "id_3",
          "role": "Identifier"
        },
        {
          "name": "id_4",
          "role": "Identifier"
        },
        {
          "name": "id_2",
          "role": "Identifier"
        },
        {
          "name": "num_1",
          "role": "Measure"
        }
      ]
    }
  ],
  "variables": [
    {
      "name": "id_2",
      "domain": "string"
    },
    {
      "name": "id_3",
      "domain": "string"
    },
    {
      "name": "id_4",
      "domain": "string"
    },
    {
      "name": "id_1",
      "domain": "number"
    },
    {
      "name": "le",
      "domain": "boolean"
    },
    {
      "name": "bool_var",
      "domain": "boolean"
    },
    {
      "name": "num_1",
      "domain": "number"
    }
  ]
}
